### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#10]
**User story**
As a potential customer, I want to clearly have available to me what the boxing club is able to offer my child

**Acceptance criteria**

- [x] The website contains a dedicated section with details about the club and what it offers
- [x] The section is clearly visible and accessible from all parts of the website.
- [x] The section contains a table clearly showing days, times and age group lessons available.

**Tasks**

- [x] Design and place a section for about us and what the club offers.
- [x] Ensure the about us section is clearly visible and accessible from all parts of the website, adhering to common design standards.
