### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#11]
**User story**
As a guardian, after going through the whole website I'll want a section where I can immediately sign up my child.

**Acceptance criteria**

- [x] The website contains a dedicated section for sign up.
- [x] The section is clearly visible and accessible from all parts of the website.
- [x] After sign up you are taken to a success page.
- [x] Pricing is clearly visible

**Tasks**

- [x] Design and place for sign up.
- [x] Ensure the contact section is clearly visible and accessible from all parts of the website, adhering to common design standards.
- [x] Success page also displays info sent to the user.
