### ISSUE TITLE
Photo gallery

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#13]
**User story**
As a potential customer, I want to see images of real people and of the club facilities themselves thus making it easier to make a decision.

**Acceptance criteria**

- [ ] Add images of the boxing club facilities.
- [ ] Give detailed descriptions.
- [ ] Add tournament photos

**Tasks**

- [ ] Incorporate and combine images and descriptions together leaving a satisfying user experience.
