### ISSUE TITLE
High quality images and engaging descriptions

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#2]
**User story**
As someone interested in historical artefacts, I want to see high-quality images and engaging descriptions of the acropolis.

**Acceptance criteria**

- [ ] The homepage features a carousel with high-quality images of the acropolis that rotates automatically that allows manual navigation.
- [ ] Engaging descriptions of the acropolis immersed in historical facts and findings over the years.
- [ ] The homepage layout prominently features the images and descriptions in an uncluttered manner.

**Tasks**

- [ ] Integrate high-quality images of the Acropolis with some of the available tourist options available today.
- [ ] Embed the descriptions and list services available today for potential tourists within the site's content.
- [ ] Design and implement a homepage layout that prominently features the images and descriptions.
