### ISSUE TITLE
Location, contact details and opening hours

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#3]
**User story**
As a potential visitor, I need to find essential information such as location, contact details, and opening hours clearly and concisely, so I can easily plan my visit or get in touch with customer services on site.

**Acceptance criteria**

- [ ] The website contains a dedicated section for location, contact details and opening hours.
- [ ] The section is clearly visible and accessible from all parts of the website.

**Tasks**

- [ ] Design and place a section for location, contact details and opening hours.
- [ ] Ensure the contact section is clearly visible and accessible from all parts of the website, adhering to common design standards.
