### ISSUE TITLE
Facts and options library

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#4]
**User story**
As a potential visitor or interested party, I want to explore and read about as many facts about the site and options available to me should I decide to visit thus making it easier to make a decision.

**Acceptance criteria**

- [ ] Add images of the described options.
- [ ] Give detailed descriptions.

**Tasks**

- [ ] Incorporate and combine images and descriptions together leaving a satisfying user experience.
