### ISSUE TITLE
Visible pricing,available discounts and busy seasons/times

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#5]
**User story**
As a family, I want to find clear information about upcoming events, pricing and any discounts so I can plan my visit within my budget and time constraints,

**Acceptance criteria**

- [ ] Clear and accurate pricing information for visitors is displayed and easy to find.
- [ ] Clearly show busy seasons and busy times using a chart

**Tasks**

- [ ] Display pricing using the provided rate information.
- [ ] Clearly display any student, family or group discounts if available.
