### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#7]
**User story**
As a potential visitor, I want to read testimonials and reviews from other visitors, so I can gauge the experience of others and feel more confident about visiting.

**Acceptance criteria**

- [ ] he website includes a section dedicated to displaying customer testimonials and reviews.
- [ ] Testimonials are clearly visible and presented in a format that is easy to read and navigate.

**Tasks**

- [ ] Create a static section on the website for customer testimonials.
- [ ] Populate this section with a selection of pre-written testimonials.
