### ISSUE TITLE
Location, contact details and opening hours

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/boardwalk-games1#9]
**User story**
As a potential visitor, I need to find essential information such as location, contact details, and opening hours clearly and concisely, so I can easily plan my visit or get in touch with with the club for possible inquiries.

**Acceptance criteria**

- [x] The website contains a dedicated section for location, contact details and opening hours.
- [x] The section is clearly visible and accessible from all parts of the website.
- [x] Links to social media platforms that open in a new tab when clicked.

**Tasks**

- [x] Design and place a section for location, contact details and opening hours.
- [x] Ensure the contact section is clearly visible and accessible from all parts of the website, adhering to common design standards.
